spring:
    datasource:
      url: jdbc:mysql://localhost:3306/woc
      username: root
      password: dyc121654
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  #指定mybatis全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #*表示所有映射文件